from threading import Thread
from typing import Callable

class MultiThread(Thread):
    def __init__(self, func: Callable[[], None], elapse: float) -> None: ...
    @property
    def func(self) -> Callable[[], None]: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
