class Percent(float):
    def __new__(cls, whole: float) -> Percent: ...
    def __init__(self, whole: int) -> None: ...
    @property
    def whole(self) -> float: ...
    @property
    def part(self) -> int: ...
    @part.setter
    def part(self, value: int) -> None: ...
    @property
    def value(self) -> float: ...
