from smoothprogressbar.__config__ import Theme as Theme
from smoothprogressbar.console import Console as Console
from smoothprogressbar.consoleprgbr import ConsolePrgBr as ConsolePrgBr
from smoothprogressbar.elapse import ElapseTime as ElapseTime
from smoothprogressbar.multithreading import MultiThread as MultiThread
from smoothprogressbar.percent import Percent as Percent

class SmoothProgressBar:
    def __init__(self, enable_elapse: bool = ..., enable_msg: bool = ..., debug: bool = ...) -> None: ...
    @property
    def msg(self) -> str: ...
    @msg.setter
    def msg(self, msg: str) -> None: ...
    def start(self, max_value: int) -> None: ...
    def stop(self) -> None: ...
    def update(self, value: int, msg: str = ...) -> None: ...
